// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGY7QFO_WbLAgN6RJZXbJTFXK-Ct7U2F0',
    appId: '1:309464982219:web:50d80a3850465cd4e5b14e',
    messagingSenderId: '309464982219',
    projectId: 'testfirestore-9b0b0',
    authDomain: 'testfirestore-9b0b0.firebaseapp.com',
    databaseURL: 'https://testfirestore-9b0b0-default-rtdb.firebaseio.com',
    storageBucket: 'testfirestore-9b0b0.firebasestorage.app',
    measurementId: 'G-9W0J2MX64H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqerBFkr_2S8ceHH233S8WqYC_hCIf7U',
    appId: '1:309464982219:android:119cbd450170176be5b14e',
    messagingSenderId: '309464982219',
    projectId: 'testfirestore-9b0b0',
    databaseURL: 'https://testfirestore-9b0b0-default-rtdb.firebaseio.com',
    storageBucket: 'testfirestore-9b0b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnWcAAnUOalcLr-znT3QLsYNy_FMxlTLM',
    appId: '1:309464982219:ios:5d16eba09b1ac674e5b14e',
    messagingSenderId: '309464982219',
    projectId: 'testfirestore-9b0b0',
    databaseURL: 'https://testfirestore-9b0b0-default-rtdb.firebaseio.com',
    storageBucket: 'testfirestore-9b0b0.firebasestorage.app',
    androidClientId: '309464982219-r5h31el51v57ss9hgo1vrs5uukbbgrtq.apps.googleusercontent.com',
    iosClientId: '309464982219-5fl698i39s0p7u4knfea327cpn706mem.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnWcAAnUOalcLr-znT3QLsYNy_FMxlTLM',
    appId: '1:309464982219:ios:5d16eba09b1ac674e5b14e',
    messagingSenderId: '309464982219',
    projectId: 'testfirestore-9b0b0',
    databaseURL: 'https://testfirestore-9b0b0-default-rtdb.firebaseio.com',
    storageBucket: 'testfirestore-9b0b0.firebasestorage.app',
    androidClientId: '309464982219-r5h31el51v57ss9hgo1vrs5uukbbgrtq.apps.googleusercontent.com',
    iosClientId: '309464982219-5fl698i39s0p7u4knfea327cpn706mem.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNDnynL9aR1RUyykC9iNfceWiF1Geibw',
    appId: '1:309464982219:web:1d92a8ffbdb36defe5b14e',
    messagingSenderId: '309464982219',
    projectId: 'testfirestore-9b0b0',
    authDomain: 'testfirestore-9b0b0.firebaseapp.com',
    databaseURL: 'https://testfirestore-9b0b0-default-rtdb.firebaseio.com',
    storageBucket: 'testfirestore-9b0b0.firebasestorage.app',
    measurementId: 'G-CTB136B24P',
  );
}
